/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.miguelefernando.notasloja.view;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import com.miguelefernando.DAO.PessoaDAO;
import com.miguelefernando.notasloja.utils.Mock;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Painel que serve como menu, é usado para acessar<br>
 * outro painéis 
 *
 * @author Miguel
 * @since 03/24
 * @version 1.0
 */
public class Painel_clientes extends javax.swing.JPanel {

    /**
     * Creates new form Painel_clientes
     * @author Miguel
     * @since 03/24
     * @version 1.0
     */
    public Painel_clientes() {
        initComponents();
        abrirTabela();
        bt_voltar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbutton_visualizarCliente = new javax.swing.JButton();
        jbutton_procurarCliente = new javax.swing.JButton();
        jbutton_CadastrarCliente = new javax.swing.JButton();
        jbutton_deletar_cliente1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_tabela = new javax.swing.JTable();
        bt_voltar = new javax.swing.JButton();
        bt_atualizarCadastro = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbutton_visualizarCliente.setText("Visualizar Cliente");
        jbutton_visualizarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutton_visualizarClienteMouseClicked(evt);
            }
        });
        add(jbutton_visualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, 51));

        jbutton_procurarCliente.setText("Procurar cliente");
        jbutton_procurarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutton_procurarClienteMouseClicked(evt);
            }
        });
        add(jbutton_procurarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 190, 51));

        jbutton_CadastrarCliente.setText("Cadastrar Cliente");
        jbutton_CadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutton_CadastrarClienteMouseClicked(evt);
            }
        });
        add(jbutton_CadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 190, 51));

        jbutton_deletar_cliente1.setText("Deletar Cliente");
        jbutton_deletar_cliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutton_deletar_cliente1MouseClicked(evt);
            }
        });
        add(jbutton_deletar_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 190, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("BALULAK");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jtable_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Cliente", "Nome Cliente", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtable_tabela);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 400, 410));

        bt_voltar.setText("Voltar");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 190, 50));

        bt_atualizarCadastro.setText("Atualizar Cadastro");
        bt_atualizarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_atualizarCadastroMouseClicked(evt);
            }
        });
        add(bt_atualizarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, 50));

        jRadioButton1.setText("mock");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    /**
    * abre o painelPerfilClientes passando nome, id e cpf do cliente
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void jbutton_visualizarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutton_visualizarClienteMouseClicked
        
        String nome = (String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 1);
        String id = (String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 0);
        String cpf = (String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 2);
        Janela.p2 = new Painel_PerfilCliente(nome, id, cpf);
        JFrame maininterface = (JFrame) SwingUtilities.getWindowAncestor(this);
        maininterface.getContentPane().remove(this);
        maininterface.add(Janela.p2, BorderLayout.CENTER);
        maininterface.pack();
    }//GEN-LAST:event_jbutton_visualizarClienteMouseClicked
    /**
    * Mostra um JOptionPane que filtra os nomes do <br>
    * cliente, no jtable, para mostrar apenas o nome <br>
    * colocado no JOptionPane
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void jbutton_procurarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutton_procurarClienteMouseClicked

        String textoDigitado = JOptionPane.showInputDialog(null, " digite o nome do cliente!");
        textoDigitado = textoDigitado.toUpperCase();
        PessoaDAO pessoa = new PessoaDAO();
        ArrayList<PessoaDAO> listaPessoa;
        listaPessoa = (ArrayList<PessoaDAO>) pessoa.listarPessoasDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();

        for (int i = listaPessoa.size() - 1; i >= 0; i--) {
            modelo.removeRow(i);
            String nomeCliente = String.valueOf(listaPessoa.get(i).getNome());
            String id = String.valueOf(listaPessoa.get(i).getId());
            if (nomeCliente.equals(textoDigitado)) {
                String[] linha = {
                    id,
                    listaPessoa.get(i).getNome(),
                    listaPessoa.get(i).getCpf()
                };

                modelo.addRow(linha);
            }
        }
        jtable_tabela.changeSelection(0, 0, false, false);
        bt_voltar.setVisible(true);


    }//GEN-LAST:event_jbutton_procurarClienteMouseClicked
    /**
    * Abre o painel Cadastro
    * 
    * @param evt java.awt.event.MouseEvent 
    * 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void jbutton_CadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutton_CadastrarClienteMouseClicked
        Janela.p4 = new Painel_cadastro();
        JFrame maininterface = (JFrame) SwingUtilities.getWindowAncestor(this);
        maininterface.getContentPane().remove(this);
        maininterface.add(Janela.p4, BorderLayout.CENTER);
        maininterface.pack();
    }//GEN-LAST:event_jbutton_CadastrarClienteMouseClicked
    /**
    * Abre o Painel atualizarCadastro passsando o id do cliente
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 05/24
    * @version 1.0
    */
    private void bt_atualizarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_atualizarCadastroMouseClicked
        int id = Integer.valueOf((String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 0));
        Janela.p5 = new Painel_atualizar_cadastro(id);
        JFrame maininterface = (JFrame) SwingUtilities.getWindowAncestor(this);
        maininterface.getContentPane().remove(this);
        maininterface.add(Janela.p5, BorderLayout.CENTER);
        maininterface.pack();
        
    }//GEN-LAST:event_bt_atualizarCadastroMouseClicked
    /**
    * inicializa o mock!
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 05/24
    * @version 1.0
    */
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
        Mock mock = new Mock();
        mock.init();
        abrirTabela();
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    /**
    * torna o botão voltar não visível quando clicado e reinicia o jtable
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 05/24
    * @version 1.0
    */
    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        bt_voltar.setVisible(false);
        abrirTabela();
    }//GEN-LAST:event_bt_voltarActionPerformed

    /**
    * deleta o cliente selecionado da tabela e do banco de dados
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 05/24
    * @version 1.0
    */
    private void jbutton_deletar_cliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutton_deletar_cliente1MouseClicked
        PessoaDAO pessoa = new PessoaDAO();
        ArrayList<PessoaDAO> listaPessoa;
        listaPessoa = (ArrayList<PessoaDAO>) pessoa.listarPessoasDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();
        int selectedRow = jtable_tabela.getSelectedRow();
        int id = Integer.parseInt((String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 0));
        System.out.println("id do excluido : "+ id);
        PessoaDAO pessoaExcluida = pessoa.getPessoa(id);
        pessoaExcluida.excluir();
        abrirTabela();
    }//GEN-LAST:event_jbutton_deletar_cliente1MouseClicked

    /**
    * Coloca os dados do Banco de dados n jtable
    * @author Miguel
    * @since 03/24
    * @version 1.0
    */
    public void abrirTabela() {
        
        
        PessoaDAO pessoa = new PessoaDAO();
        ArrayList<PessoaDAO> listaPessoa;
        listaPessoa = (ArrayList<PessoaDAO>) pessoa.listarPessoasDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();
        
        modelo.setRowCount(0);
        for (int i = 0; i < listaPessoa.size(); i++) {
            String idString = String.valueOf(listaPessoa.get(i).getId());
            String[] linha = {
                idString,
                listaPessoa.get(i).getNome(),
                listaPessoa.get(i).getCpf()
            };
            modelo.addRow(linha);
        }
        jtable_tabela.changeSelection(0, 0, false, false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizarCadastro;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbutton_CadastrarCliente;
    private javax.swing.JButton jbutton_deletar_cliente1;
    private javax.swing.JButton jbutton_procurarCliente;
    private javax.swing.JButton jbutton_visualizarCliente;
    private javax.swing.JTable jtable_tabela;
    // End of variables declaration//GEN-END:variables
}
