/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miguelefernando.notasloja.view;

import com.miguelefernando.DAO.PedidoDAO;
import com.miguelefernando.DAO.PessoaDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Painel_PerfilCliente extends javax.swing.JPanel {

    /**
     * Creates new form Painel_PerfilCliente
     */
    public Painel_PerfilCliente(String nome, String id, String cpf) {
        initComponents();
        setLabels(nome, id, cpf);
        setTabela(id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lb_foto = new javax.swing.JLabel();
        lb_nome = new javax.swing.JLabel();
        lb_cpf = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabela = new javax.swing.JTable();
        bt_relatorio = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_foto.setText("jLabel1");
        add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        lb_nome.setText("jLabel2");
        add(lb_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, -1));

        lb_cpf.setText("jLabel4");
        add(lb_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        lb_id.setText("jLabel5");
        add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, -1));

        jt_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Pedido", "Valor Total", "Emissão", "Fechamento", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_tabela);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, 200));

        bt_relatorio.setText("Relatório");
        add(bt_relatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 120, 40));

        bt_voltar.setText("Voltar");
        add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void setLabels(String nome, String id, String cpf){
        lb_nome.setText(nome);
        lb_id.setText(id);
        lb_cpf.setText(cpf);
    }
    
    public void setTabela(String id){
        
        PedidoDAO pedido = new PedidoDAO();
        ArrayList<PedidoDAO> listaPedido;
        listaPedido = (ArrayList<PedidoDAO>) pedido.listarPedidosDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jt_tabela.getModel();
        
        for(int i = 0; i < listaPedido.size(); i++ ){
            String idCliente = String.valueOf(listaPedido.get(i).getId_cliente());
            if(idCliente.equals(id)){
            String idString = String.valueOf(listaPedido.get(i).getId());
            String valorTotal = String.valueOf(listaPedido.get(i).getTotal());
            String emissao = String.valueOf(listaPedido.get(i).getEmissao());
            String fechamento = String.valueOf(listaPedido.get(i).getFechamento());
            String status = String.valueOf(listaPedido.get(i).getStatus());
            String [] linha = {
                idString,
                valorTotal,
                emissao,
                fechamento,
                status
                
            };
            modelo.addRow(linha);
        }
    }
        jt_tabela.changeSelection(0, 0, false, false);
}
    
    public void qualquercoisa(){
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_relatorio;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_tabela;
    private javax.swing.JLabel lb_cpf;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nome;
    // End of variables declaration//GEN-END:variables
}
