/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.miguelefernando.notasloja.view;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import com.miguelefernando.DAO.PessoaDAO;
import com.miguelefernando.notasloja.utils.Mock;
import java.awt.event.KeyEvent;
import java.util.ArrayList;


/**
 * Painel que serve como menu, é usado para acessar<br>
 * outros painéis 
 *
 * @author Miguel
 * @since 04/24
 * @version 1.0
 * 
 */
import static com.miguelefernando.notasloja.view.Janela.idioma1;
import static com.miguelefernando.notasloja.view.Janela.pais1;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.Principal;
import java.util.Locale;
import java.util.PropertyResourceBundle;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Painel_clientes extends javax.swing.JPanel {
    public String message;
    public ResourceBundle traducoes1; 

    /**
     * Creates new form Painel_clientes
     * @author Miguel
     * @since 04/24
     * @version 1.0
     */
    public Painel_clientes() {
        initComponents();
        abrirTabela();
        
        bt_voltarClientes.setVisible(false);
      
        ResourceBundle traducoes = null;
        InputStream newInputStream;
  
        String nomeArquivo = "./idiomas/MessagesBundle_"+idioma1+"_"+pais1+".properties";
        System.out.println(nomeArquivo);
        try {
            newInputStream = Files.newInputStream(Paths.get(nomeArquivo));
            traducoes = new PropertyResourceBundle(newInputStream);
            System.out.println(traducoes);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        traducoes1 = traducoes;
        

        message = traducoes.getString("message");
 
        
        

        
        
        bt_vizualizarCliente.setText(traducoes.getString("bt_vizualizar"));
        bt_procurarCliente.setText(traducoes.getString("bt_procurar"));
        bt_voltarClientes.setText(traducoes.getString("bt_voltar"));
        bt_deletarClientes.setText(traducoes.getString("bt_deletar"));
        bt_atualizarCadastro.setText(traducoes.getString("bt_atuzalizar"));
        bt_cadastrarClientes.setText(traducoes.getString("bt_cadastro"));
        
        
        lingua_tabela(traducoes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_vizualizarCliente = new javax.swing.JButton();
        bt_procurarCliente = new javax.swing.JButton();
        bt_cadastrarClientes = new javax.swing.JButton();
        bt_deletarClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_tabela = new javax.swing.JTable();
        bt_voltarClientes = new javax.swing.JButton();
        bt_atualizarCadastro = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_vizualizarCliente.setText("Visualizar Cliente");
        bt_vizualizarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_vizualizarClienteMouseClicked(evt);
            }
        });
        add(bt_vizualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, 51));

        bt_procurarCliente.setText("Procurar cliente");
        bt_procurarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_procurarClienteMouseClicked(evt);
            }
        });
        add(bt_procurarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 190, 51));

        bt_cadastrarClientes.setText("Cadastrar Cliente");
        bt_cadastrarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cadastrarClientesMouseClicked(evt);
            }
        });
        add(bt_cadastrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 190, 51));

        bt_deletarClientes.setText("Deletar Cliente");
        bt_deletarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_deletarClientesMouseClicked(evt);
            }
        });
        add(bt_deletarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 190, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("BALULAK");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jtable_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Cliente", "Nome Cliente", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtable_tabela);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 400, 410));

        bt_voltarClientes.setText("Voltar");
        bt_voltarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarClientesActionPerformed(evt);
            }
        });
        add(bt_voltarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 190, 50));

        bt_atualizarCadastro.setText("Atualizar Cadastro");
        bt_atualizarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_atualizarCadastroMouseClicked(evt);
            }
        });
        add(bt_atualizarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, 50));

        jRadioButton1.setText("mock");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    /**
    * abre o painelPerfilClientes passando nome, id e cpf do cliente
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void bt_vizualizarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_vizualizarClienteMouseClicked
        
        String nome = (String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 1);
        String id = (String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 0);
        String cpf = (String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 2);
        Janela.p2 = new Painel_PerfilCliente(nome, id, cpf);
        JFrame maininterface = (JFrame) SwingUtilities.getWindowAncestor(this);
        maininterface.getContentPane().remove(this);
        maininterface.add(Janela.p2, BorderLayout.CENTER);
        maininterface.pack();
    }//GEN-LAST:event_bt_vizualizarClienteMouseClicked
    /**
    * Mostra um JOptionPane que filtra os nomes do <br>
    * cliente, no jtable, para mostrar apenas o nome <br>
    * colocado no JOptionPane
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void bt_procurarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_procurarClienteMouseClicked

        
        String textoDigitado = JOptionPane.showInputDialog(null, message);
        textoDigitado = textoDigitado.toUpperCase();
        PessoaDAO pessoa = new PessoaDAO();
        ArrayList<PessoaDAO> listaPessoa;
        listaPessoa = (ArrayList<PessoaDAO>) pessoa.listarPessoasDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();

        for (int i = listaPessoa.size() - 1; i >= 0; i--) {
            modelo.removeRow(i);
            String nomeCliente = String.valueOf(listaPessoa.get(i).getNome());
            String id = String.valueOf(listaPessoa.get(i).getId());
            if (nomeCliente.equals(textoDigitado)) {
                String[] linha = {
                    id,
                    listaPessoa.get(i).getNome(),
                    listaPessoa.get(i).getCpf()
                };

                modelo.addRow(linha);
            }
        }
        jtable_tabela.changeSelection(0, 0, false, false);
        bt_voltarClientes.setVisible(true);


    }//GEN-LAST:event_bt_procurarClienteMouseClicked
    /**
    * Abre o painel Cadastro
    * 
    * @param evt java.awt.event.MouseEvent 
    * 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void bt_cadastrarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastrarClientesMouseClicked
        Janela.p4 = new Painel_cadastro();
        JFrame maininterface = (JFrame) SwingUtilities.getWindowAncestor(this);
        maininterface.getContentPane().remove(this);
        maininterface.add(Janela.p4, BorderLayout.CENTER);
        maininterface.pack();
    }//GEN-LAST:event_bt_cadastrarClientesMouseClicked
    /**
    * Abre o Painel atualizarCadastro passsando o id do cliente
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void bt_atualizarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_atualizarCadastroMouseClicked
        int id = Integer.valueOf((String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 0));
        Janela.p5 = new Painel_atualizar_cadastro(id);
        JFrame maininterface = (JFrame) SwingUtilities.getWindowAncestor(this);
        maininterface.getContentPane().remove(this);
        maininterface.add(Janela.p5, BorderLayout.CENTER);
        maininterface.pack();
        
    }//GEN-LAST:event_bt_atualizarCadastroMouseClicked
    /**
    * inicializa o mock!
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
        Mock mock = new Mock();
        mock.init();
        abrirTabela();
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    /**
    * torna o botão voltar não visível quando clicado e reinicia o jtable
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void bt_voltarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarClientesActionPerformed
        bt_voltarClientes.setVisible(false);
        abrirTabela();
    }//GEN-LAST:event_bt_voltarClientesActionPerformed

    /**
    * deleta o cliente selecionado da tabela e do banco de dados
    * @param evt java.awt.event.MouseEvent 
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    private void bt_deletarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_deletarClientesMouseClicked
        PessoaDAO pessoa = new PessoaDAO();
        ArrayList<PessoaDAO> listaPessoa;
        listaPessoa = (ArrayList<PessoaDAO>) pessoa.listarPessoasDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();
        int selectedRow = jtable_tabela.getSelectedRow();
        int id = Integer.parseInt((String) jtable_tabela.getValueAt(jtable_tabela.getSelectedRow(), 0));
        PessoaDAO pessoaExcluida = pessoa.getPessoa(id);
        pessoaExcluida.excluir(traducoes1);
        abrirTabela();
    }//GEN-LAST:event_bt_deletarClientesMouseClicked

    /**
    * Coloca os dados do Banco de dados n jtable
    * @author Miguel
    * @since 04/24
    * @version 1.0
    */
    public void abrirTabela() {
        
        
        PessoaDAO pessoa = new PessoaDAO();
        ArrayList<PessoaDAO> listaPessoa;
        listaPessoa = (ArrayList<PessoaDAO>) pessoa.listarPessoasDAO();
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();
        
        modelo.setRowCount(0);
        for (int i = 0; i < listaPessoa.size(); i++) {
            String idString = String.valueOf(listaPessoa.get(i).getId());
            String[] linha = {
                idString,
                listaPessoa.get(i).getNome(),
                listaPessoa.get(i).getCpf()
            };
            modelo.addRow(linha);
        }
        jtable_tabela.changeSelection(0, 0, false, false);
    }
    
    public void lingua_tabela(ResourceBundle traducoes){
        String [] novonome = {traducoes.getString("id_cliente"), traducoes.getString("nome_cliente"), traducoes.getString("cpf_cliente")}; 
        DefaultTableModel modelo = (DefaultTableModel) this.jtable_tabela.getModel();
        modelo.setColumnIdentifiers(novonome);
        jtable_tabela.setModel(modelo);
   
        
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizarCadastro;
    private javax.swing.JButton bt_cadastrarClientes;
    private javax.swing.JButton bt_deletarClientes;
    private javax.swing.JButton bt_procurarCliente;
    private javax.swing.JButton bt_vizualizarCliente;
    private javax.swing.JButton bt_voltarClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable_tabela;
    // End of variables declaration//GEN-END:variables
}
